version: 2

project_name: kubectl-container_status

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: kubectl-container_status
    binary: kubectl-container_status
    main: ./cmd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: kubectl-container_status
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: nareshku
    name: kubectl-container_status
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## kubectl container-status {{.Version}}
    
    A kubectl plugin for displaying container-level status and diagnostics with enhanced visual design.
    
    ### ✨ Visual Enhancements
    - 🟢🟡🔴 Modern emoji status indicators
    - 📦 Bordered health status display  
    - ⚠️🚨ℹ️ Categorized event icons
    - 🎯 Professional header layout
    
    ### 🛠️ Core Features
    - Smart container health analysis
    - Cross-platform support
    - Multiple output formats (table, JSON, YAML)
    - Problematic pod filtering
    - Resource usage visualization
  footer: |
    ## Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### Install as kubectl plugin
    ```bash
    # Download the binary (replace with your platform)
    curl -LO https://github.com/nareshku/kubectl-container_status/releases/download/{{.Tag}}/kubectl-container-status_{{.Version}}_linux_amd64.tar.gz
    
    # Extract and install
    tar -xzf kubectl-container-status_{{.Version}}_linux_amd64.tar.gz
    chmod +x kubectl-container_status
    sudo mv kubectl-container_status /usr/local/bin/
    
    # Verify installation
    kubectl container-status --help
    ```
    
    ### Other platforms
    - **macOS**: Replace `linux_amd64` with `darwin_amd64` or `darwin_arm64`
    - **Windows**: Download the `.zip` file instead of `.tar.gz` 